import db
conn = db.connect()
cursor = conn.cursor()
cursor.execute("SELECT status, COUNT(*) FROM leads GROUP BY status")
data = cursor.fetchall()
print("Lead Status Counts:", data)
cursor.execute("SELECT id, full_name, status FROM leads")
leads = cursor.fetchall()
print("All Leads:", leads)
conn.close()
